{
 "title": "Nest metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heating status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\"nest.heating_status\"}"
    }
   ]
  },
  {
   "title": "Eco mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\"nest.eco_mode\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"nest.current_temp\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"nest.humidity\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nest.current_temp\"}",
     "legendFormat": "Temperature over time"
    }
   ]
  },
  {
   "title": "Humidity over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nest.humidity\"}",
     "legendFormat": "Humidity over time"
    }
   ]
  }
 ]
}